# Machine Learning Online Assignment
## Part I - NumPy

### Task 1

In [1]:
import numpy as np
import time

In [2]:
# 1.1
array_1d = np.arange(1, 11)

# 1.2
array_2d = np.arange(1, 10).reshape(3, 3)

# 1.3
array_3d = np.random.rand(3, 5, 3)

In [3]:
# 2
print("1D Array:\n", array_1d)
print("\n2D Array:\n", array_2d)
print("\n3D Array:\n", array_3d)

print("\nShapes:")
print("1D array shape:", array_1d.shape)
print("2D array shape:", array_2d.shape)
print("3D array shape:", array_3d.shape)

print("\nSizes:")
print("1D array size:", array_1d.size)
print("2D array size:", array_2d.size)
print("3D array size:", array_3d.size)

print("\nData Types:")
print("1D array dtype:", array_1d.dtype)
print("2D array dtype:", array_2d.dtype)
print("3D array dtype:", array_3d.dtype)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
 [[[0.84827826 0.73737738 0.56928039]
  [0.37020444 0.36736829 0.5595143 ]
  [0.29614597 0.27557627 0.1918785 ]
  [0.10361777 0.71768246 0.85192123]
  [0.32409621 0.3093825  0.25110124]]

 [[0.92987008 0.30119686 0.40231203]
  [0.80202544 0.85145269 0.47154129]
  [0.46654299 0.67171118 0.93499254]
  [0.90367614 0.92816134 0.83330774]
  [0.94559383 0.6715825  0.03834266]]

 [[0.90066923 0.01898787 0.70000809]
  [0.92234095 0.51352892 0.20694799]
  [0.00871417 0.38123736 0.82037569]
  [0.59292873 0.35685167 0.35095407]
  [0.05705425 0.34718784 0.96662239]]]

Shapes:
1D array shape: (10,)
2D array shape: (3, 3)
3D array shape: (3, 5, 3)

Sizes:
1D array size: 10
2D array size: 9
3D array size: 45

Data Types:
1D array dtype: int32
2D array dtype: int32
3D array dtype: float64


### Task 2

In [4]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("\nOriginal array:", data)
print("First three elements:", data[:3])
print("Every alternate element:", data[::2])
print("Reversed array:", data[::-1])


Original array: [10 20 30 40 50 60 70 80 90]
First three elements: [10 20 30]
Every alternate element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


### Task 3

In [5]:
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("\nArray A:", A)
print("Array B:", B)

print("Element-wise Addition:", A + B)
print("Element-wise Subtraction:", A - B)
print("Element-wise Multiplication:", A * B)
print("Element-wise Division:", A / B)

print("Dot Product of A and B:", np.dot(A, B))

print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Standard Deviation of A:", np.std(A))
print("Variance of A:", np.var(A))

print("Maximum value in B:", np.max(B))
print("Index of Maximum value in B:", np.argmax(B))
print("Minimum value in B:", np.min(B))
print("Index of Minimum value in B:", np.argmin(B))


Array A: [13 11 15  8  7]
Array B: [19 16 13 12  7]
Element-wise Addition: [32 27 28 20 14]
Element-wise Subtraction: [-6 -5  2 -4  0]
Element-wise Multiplication: [247 176 195  96  49]
Element-wise Division: [0.68421053 0.6875     1.15384615 0.66666667 1.        ]
Dot Product of A and B: 763
Mean of A: 10.8
Median of A: 11.0
Standard Deviation of A: 2.993325909419153
Variance of A: 8.959999999999999
Maximum value in B: 19
Index of Maximum value in B: 0
Minimum value in B: 7
Index of Minimum value in B: 4


### Task 4

In [6]:
arr = np.arange(1, 13)
print("\nOriginal 1D array:", arr)

arr_2d = arr.reshape(4, 3)
print("Reshaped into 2D array (4, 3):\n", arr_2d)

arr_3d = arr.reshape(2, 2, 3)
print("Reshaped into 3D array (2, 2, 3):\n", arr_3d)

print("Shape of Transposed 2D array (4, 3) -> (3, 4):", arr_2d.T.shape)


Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped into 2D array (4, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped into 3D array (2, 2, 3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of Transposed 2D array (4, 3) -> (3, 4): (3, 4)


### Task 5

In [7]:
arr = np.random.randint(10, 51, 15)
print("\nOriginal array:", arr)

print("Elements greater than 25:", arr[arr > 25])

arr[arr < 30] = 0
print("Array after replacing elements less than 30 with 0:", arr)

print("Number of elements divisible by 5:", np.sum(arr % 5 == 0))


Original array: [47 26 31 45 15 10 12 39 15 16 20 21 43 15 42]
Elements greater than 25: [47 26 31 45 39 43 42]
Array after replacing elements less than 30 with 0: [47  0 31 45  0  0  0 39  0  0  0  0 43  0 42]
Number of elements divisible by 5: 10


### Task 6

In [8]:
print("\nEqually spaced values between 0 and 1:", np.linspace(0, 1, 10))

identity_matrix = np.eye(4)
print("Identity matrix of size 4x4:\n", identity_matrix)

arr = np.random.randint(1, 101, 20)
print("Original random array:", arr)
print("5 largest elements:", np.sort(arr)[-5:])


Equally spaced values between 0 and 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity matrix of size 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Original random array: [67 98 78 75 88 83 88 33 15 29 71 57 44 20 78 96 16 77 87 98]
5 largest elements: [88 88 96 98 98]


### Task 7

In [9]:
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start = time.time()
C = np.dot(A, B)
end = time.time()
print("\nTime taken for matrix multiplication:", end - start, "seconds")

try:
    det = np.linalg.det(C)
    print("Determinant of result matrix:", det)

    inv = np.linalg.inv(C)
    print("Inverse of result matrix:\n", inv)
except np.linalg.LinAlgError:
    print("Inverse not possible: Matrix is singular or not invertible.")


Time taken for matrix multiplication: 0.003968954086303711 seconds
Determinant of result matrix: 3.9113607875017067e+49
Inverse of result matrix:
 [[13.85188133 -1.51278886 -2.79747028 ... 12.40662637 11.8367246
   0.64224046]
 [-7.09786236 -1.97476341  3.29459985 ... -5.06659924 -9.6405697
   1.57017531]
 [-6.04084133  1.81803849  0.19418345 ... -5.67492511 -2.49068251
  -0.64919   ]
 ...
 [-8.33438897 -1.50283282  3.30665746 ... -6.9310353  -9.76774026
   1.58625358]
 [11.62901051 -1.58770497 -2.08291791 ... 10.67815806  9.31854574
   0.58536229]
 [ 6.62460128 -1.18590903 -1.37459609 ...  5.40345676  5.02624449
   0.43937961]]
